baseURL = "https://gradshow.com.au"
languageCode = "en-us"
title = "Amplified Together"
theme = "amplified-together"

[taxonomies]
    theme = "themes"
    discipline = "disciplines"

[markup.goldmark.renderer]
    unsafe= true