[build]
publish = "public"
command = "hugo --gc --minify -s hugo"

[context.production.environment]
HUGO_VERSION = "0.76.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo -s hugo"

[context.split1.environment]
HUGO_VERSION = "0.76.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -s hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.76.3"

[context.branch-deploy]
command = "hugo --gc --minify -s hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.76.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"